### ISSUE TITLE
Error with ng start

### ISSUE THREAD

**Issue by Jin-K** [angular-university/ngrx-course#13]
Hi.

I have an error when I launch the "npm start" instruction.
I maybe tried it at a bad moment ?

This is the error's output:

> npm start
> 
> ngrx-course@0.0.0 start C:\Data\dev\tests\Angular_and_ngrx\ngrx-course
> ng serve --proxy-config proxy.conf.json
> 
> Versions of @angular/compiler-cli and typescript could not be determined.
> The most common reason for this is a broken npm install.
> 
> Please make sure your package.json contains both @angular/compiler-cli and typescript in
> devDependencies, then delete node_modules and package-lock.json (if you have one) and
> run npm install again.
> 
> npm ERR! Windows_NT 10.0.15063
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v6.11.1
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! ngrx-course@0.0.0 start: `ng serve --proxy-config proxy.conf.json`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the ngrx-course@0.0.0 start script 'ng serve --proxy-config proxy.conf.json'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ngrx-course package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ng serve --proxy-config proxy.conf.json
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ngrx-course
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ngrx-course
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Data\dev\tests\Angular_and_ngrx\ngrx-course\npm-debug.log

The log file is attached to the issue.

[npm-debug.log](https://github.com/angular-university/ngrx-course/files/1460342/npm-debug.log)

Regards

**Comment by jhades** [comment]
Hello,  I noticed in the log that this is being installed with node 6, I recommend installing the latest node 8.9.x. This is is because it comes with npm 5, which will use the package-lock.json file to install dependencies.

This will ensure the installation of the right dependencies, and everything will run smoothly.  KR Vasco

**Comment by Jin-K** [comment]
Hello, thank you for your quick feedback.

After installing the new Node and npm manager, I got it to work once.

But now, I don't know why, I have the same error message with a different log :

[2017-11-10T15_24_58_489Z-debug.log](https://github.com/angular-university/ngrx-course/files/1461807/2017-11-10T15_24_58_489Z-debug.log)
