### ISSUE TITLE
Lodash problem

### ISSUE THREAD

**Issue by djindjic** [angular-university/ngrx-course#5]
after running `npm start` I have list of errors related to lodash:

```
...
webpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] /Users/aleksandar/projects/ngrx-course/node_modules/@types/lodash/index.d.ts:244:13
    Duplicate identifier '_'.
[default] /Users/aleksandar/projects/ngrx-course/node_modules/@types/lodash/index.d.ts:244:16
    Cannot find namespace '_'.
[default] /Users/aleksandar/projects/ngrx-course/node_modules/@types/lodash/index.d.ts:246:25
    Cannot find name 'Partial'.
...
```

**Comment by LocDaiNguyen** [comment]
Its a lodash issue.

npm install @types/lodash@4.14.50 --save-dev will fix the errors

**Comment by jhades** [comment]
@djindjic thank you for reporting the issue,  @LocDaiNguyen thank you for sharing the solution it helps a lot. Please don't hesitate to comment and share solutions in the course comments where you see you could help. Thanks, Kind Regards, Vasco
